version: 2.1
jobs:
  ## Lowest GHC Version
  ghc_8_2_2:
    docker:
      - image: fpco/stack-build:lts-11.10
    steps:
      - checkout
      - restore_cache:
          name: restore cached stack
          keys:
            - stack-vesrion-{{ checksum "stack-11.10.yaml" }}
      - restore_cache:
          name: restore cached dependencies
          keys:
            - stack-dependencies-{{ checksum "stack-11.10.yaml" }}-{{ checksum "package.yaml" }}-{{ checksum "examples/package.yaml" }}
      - run:
          name: setup stack
          command: STACK_YAML=stack-11.10.yaml stack --no-terminal setup
      - save_cache:
          name: cache stack
          key: stack-vesrion-{{ checksum "stack-11.10.yaml" }}
          paths:
            - /root/.stack
      - run:
          name: install dependencies
          command: STACK_YAML=stack-11.10.yaml stack build --skip-ghc-check --no-terminal --test --only-dependencies
      - save_cache:
          name: cache dependencies
          key: stack-dependencies-{{ checksum "stack-11.10.yaml" }}-{{ checksum "package.yaml" }}-{{ checksum "examples/package.yaml" }}
          paths:
            - ".stack-work"
            - "/root/.stack"
      - run:
          name: run tests
          command: STACK_YAML=stack-11.10.yaml stack test --haddock --no-haddock-deps
      - run:
          name: Install executables
          command: STACK_YAML=stack-11.10.yaml stack install

  ghc_8_4_4:
    docker:
      - image: fpco/stack-build:lts-12.16
    steps:
      - checkout
      - restore_cache:
          name: restore cached stack
          keys:
            - stack-vesrion-{{ checksum "stack-12.16.yaml" }}
      - restore_cache:
          name: restore cached dependencies
          keys:
            - stack-dependencies-{{ checksum "stack-12.16.yaml" }}-{{ checksum "package.yaml" }}-{{ checksum "examples/package.yaml" }}
      - run:
          name: setup stack
          command: STACK_YAML=stack-12.16.yaml stack --no-terminal setup
      - save_cache:
          name: cache stack
          key: stack-vesrion-{{ checksum "stack-12.16.yaml" }}
          paths:
            - /root/.stack
      - run:
          name: install dependencies
          command: STACK_YAML=stack-12.16.yaml stack build --skip-ghc-check --no-terminal --test --only-dependencies
      - save_cache:
          name: cache dependencies
          key: stack-dependencies-{{ checksum "stack-12.16.yaml" }}-{{ checksum "package.yaml" }}-{{ checksum "examples/package.yaml" }}
          paths:
            - ".stack-work"
            - "/root/.stack"
      - run:
          name: Run tests
          command: STACK_YAML=stack-12.16.yaml stack test --haddock --no-haddock-deps
      - run:
          name: Install executables
          command: STACK_YAML=stack-12.16.yaml stack install

  ## GHC 8.6.5
  ghc_8_6_5:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - restore_cache:
          name: restore cached stack
          keys:
            - stack-vesrion-{{ checksum "stack.yaml" }}
      - restore_cache:
          name: restore cached dependencies
          keys:
            - stack-dependencies-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}-{{ checksum "examples/package.yaml" }}
      - run:
          name: setup stack
          command: stack --no-terminal setup
      - save_cache:
          name: cache stack
          key: stack-vesrion-{{ checksum "stack.yaml" }}
          paths:
            - /root/.stack
      - run:
          name: install dependencies
          command: stack build --skip-ghc-check --no-terminal --test --only-dependencies
      - save_cache:
          name: cache dependencies
          key: stack-dependencies-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}-{{ checksum "examples/package.yaml" }}
          paths:
            - ".stack-work"
            - "/root/.stack"
      - run:
          name: Run tests
          command: stack test --haddock --no-haddock-deps
      - run:
          name: Install executables
          command: stack install
  

  ## GHC 8.8.1
  ghc_8_8_1:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - restore_cache:
          name: restore cached stack
          keys:
            - stack-vesrion-{{ checksum "stack-nightly.yaml" }}
      - restore_cache:
          name: restore cached dependencies
          keys:
            - stack-dependencies-{{ checksum "stack-nightly.yaml" }}-{{ checksum "package.yaml" }}-{{ checksum "examples/package.yaml" }}
      - run:
          name: setup stack
          command: STACK_YAML=stack-nightly.yaml stack --no-terminal setup
      - save_cache:
          name: cache stack
          key: stack-vesrion-{{ checksum "stack-nightly.yaml" }}
          paths:
            - /root/.stack
      - run:
          name: install dependencies
          command: STACK_YAML=stack-nightly.yaml stack build --skip-ghc-check --no-terminal --test --only-dependencies
      - save_cache:
          name: cache dependencies
          key: stack-dependencies-{{ checksum "stack-nightly.yaml" }}-{{ checksum "package.yaml" }}-{{ checksum "examples/package.yaml" }}
          paths:
            - ".stack-work"
            - "/root/.stack"
      - run:
          name: Run tests
          command: STACK_YAML=stack-nightly.yaml stack test --haddock --no-haddock-deps
      - run:
          name: Install executables
          command: STACK_YAML=stack-nightly.yaml stack install

  check-release:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - run:
          name: generate sdist
          command: stack sdist . --tar-dir ./prod ; cd ./prod
      - run:
          name: unpack
          command: tar -zxvf morpheus-graphql-0.9.0.tar.gz ; cd morpheus-graphql-0.9.0
      - run:
          name: build prod
          command: cabal build
      - run:
          name: tests prod
          command: cabal test

workflows:
  version: 2.1
  build_all:
    jobs:
      - ghc_8_2_2
      - ghc_8_4_4
      - ghc_8_6_5
      - ghc_8_8_1
      - check-release