bounds:
  - 0.20.0
  - 0.21.0
examples:
  - examples/scotty
  - examples/scotty-freer-simple
  - examples/servant
  - examples/client
  - examples/code-gen
packages:
  - morpheus-graphql-tests
  - morpheus-graphql-core
  - morpheus-graphql-code-gen
  - morpheus-graphql-app
  - morpheus-graphql-client
  - morpheus-graphql-subscriptions
  - morpheus-graphql
plan:
  8.10.7:
    deps:
      dependent-map: 0.2.4.0
      dependent-sum: 0.4
      graphql: 0.11.1.0
    include:
      - morpheus-graphql-benchmarks
    resolver: lts-18.10
  8.2.2:
    resolver: lts-11.10
  8.4.4:
    deps:
      aeson: 1.4.4.0
      base-orphans: 0.8.1
      fastsum: 0.1.0.0
      megaparsec: 7.0.5
      modern-uri: 0.3.0.0
      relude: 0.3.0
      req: 2.1.0
      retry: 0.8.1.0
      time-compat: 1.9.2.2
    resolver: lts-12.16
  8.6.5:
    resolver: lts-14.14
  8.8.3:
    resolver: lts-16.2
  latest:
    deps:
      fastsum: 0.1.1.1
      fraxl: 0.3.0.0
      haxl: 2.4.0.0
      type-aligned: 0.9.6
    resolver: nightly-2022-03-02
    skip:
      - examples/scotty
rules:
  aeson:
    - 1.4.4
    - 3.0.0
  base:
    - 4.7.0
    - 5.0.0
  bytestring:
    - 0.10.4
    - 0.12.0
  containers:
    - 0.4.2.1
    - 0.7.0
  directory:
    - 1.0.0
    - 2.0.0
  file-embed:
    - 0.0.10
    - 1.0.0
  filepath:
    - 1.1.0
    - 1.5.0
  hashable:
    - 1.0.0
    - 2.0.0
  megaparsec:
    - 7.0.0
    - 10.0.0
  mtl:
    - 2.0.0
    - 3.0.0
  optparse-applicative:
    - 0.12.0
    - 0.18.0
  prettyprinter:
    - 1.2.0
    - 2.0.0
  relude:
    - 0.3.0
    - 2.0.0
  scientific:
    - 0.3.6.2
    - 0.4.0
  tasty:
    - 0.1.0
    - 1.5.0
  tasty-hunit:
    - 0.1.0
    - 1.0.0
  template-haskell:
    - 2.0.0
    - 3.0.0
  text:
    - 1.2.3
    - 1.3.0
  th-lift-instances:
    - 0.1.1
    - 0.3.0
  transformers:
    - 0.3.0
    - 0.6.0
  unliftio-core:
    - 0.0.1
    - 0.4.0
  unordered-containers:
    - 0.2.8
    - 0.3.0
  uuid:
    - 1.0.0
    - 1.4.0
  vector:
    - 0.12.0.1
    - 0.13.0
  websockets:
    - 0.11.0
    - 1.0.0
version: 0.20.0
