resolver: lts-11.10
save-hackage-creds: false
packages:
  - examples/scotty
  - examples/scotty-freer-simple
  - examples/servant
  - examples/client
  - examples/code-gen
  - morpheus-graphql-tests
  - morpheus-graphql-core
  - morpheus-graphql-code-gen
  - morpheus-graphql-app
  - morpheus-graphql-client
  - morpheus-graphql-subscriptions
  - morpheus-graphql
extra-deps:
  - aeson-1.4.4.0
  - base-orphans-0.8.1
  - dependent-map-0.2.4.0
  - dependent-sum-0.4
  - fastsum-0.1.0.0
  - fraxl-0.3.0.0
  - graphql-0.11.1.0
  - haxl-2.4.0.0
  - megaparsec-7.0.5
  - modern-uri-0.3.0.0
  - relude-0.3.0
  - req-2.1.0
  - retry-0.8.1.0
  - time-compat-1.9.2.2
  - type-aligned-0.9.6
