name: ci for cabal sdist

on: [push]

env:
  DIST_PATH: "/home/runner/morpheus-graphql-dist"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.6.5'
        cabal-version: '3.0'
    - name: Install dependencies
      run: | 
        # bash release.sh
        cabal update
        cabal build --only-dependencies
    - name: Build
      run: |
        # cd $DIST_PATH
        # cd release
        # echo $PWD
        # ls
        cabal configure --enable-tests
        cabal build
    - name: Run tests
      run: |
        # cd $DIST_PATH
        # cd release
        # echo $PWD
        # ls
        cabal test
