name: CI
on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
jobs:
  build:
    strategy:
      matrix:
        # "8.2.2"  TODO: fix: ByteCodeLink.lookupCE
        ghc: ["8.4.4", "8.6.5", "8.8.3", "8.10.7", "latest"]
        os: [ubuntu-latest]
      fail-fast: true
    runs-on: ${{ matrix.os }}
    name: GHC ${{ matrix.ghc}} (${{ matrix.os }})
    steps:
      - uses: actions/checkout@v2
      - name: setup stack config
        run: cp config/stack/${{ matrix.ghc }}.yaml  stack.yaml

      - name: Setup Haskell
        uses: haskell/actions/setup@v1.2
        with:
          ghc-version: ${{ matrix.ghc }}
          enable-stack: true
      - name: Cache Stack
        uses: actions/cache@v2
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ matrix.ghc }}-stack-${{ hashFiles('stack.yaml') }}-packages-${{ hashFiles('**/package.yaml') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-stack-${{ hashFiles('stack.yaml') }}
            ${{ runner.os }}-${{ matrix.ghc }}-stack-

      # Install & Build & Test

      - name: Install dependencies
        run: |
          stack build --fast --skip-ghc-check --no-terminal --test --only-dependencies

      - name: Build
        run: |
          stack build --fast --test --bench --no-run-tests --no-run-benchmarks --haddock --no-haddock-deps

      - name: Test
        run: |
          stack test --fast

  hlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: lint
        run: |
          curl -sSL https://raw.github.com/ndmitchell/hlint/master/misc/run.sh | sh -s .

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
